name: Awesome xonshrc test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          echo $(python -V)
          python -m pip install --upgrade pip
          pip install 'xonsh[full]'
      - name: Install awesome RC
        run: |
          pip install .
      - name: Test awesome RC
        run: |
          echo Get xontrib name
          filename=$(basename -- $(ls xontrib/*.*))
          xontrib_name="${filename%.*}"
          echo Xontrib name: $xontrib_name
          echo Testing...
          export XONSH_SHOW_TRACEBACK=True
          xonsh -c "xontrib load $xontrib_name"
